# Generated by Django 4.1.2 on 2022-10-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderproduct_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='size',
            new_name='capacity',
        ),
    ]
