# Generated by Django 4.1.2 on 2022-10-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_variations_options_variations_variation_value'),
        ('orders', '0003_rename_size_orderproduct_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(to='products.variations'),
        ),
    ]
