# Generated by Django 4.1.2 on 2022-10-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='capacity',
        ),
    ]
