# Generated by Django 4.1.1 on 2022-09-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_title_product_p_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_title',
            new_name='title',
        ),
    ]
