# Generated by Django 4.1.1 on 2022-09-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_p_title_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default-store-350x350.jpg', upload_to='products/%y/%m/%d'),
        ),
    ]
