# Generated by Django 4.1.1 on 2022-10-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'Variation'},
        ),
        migrations.AddField(
            model_name='variations',
            name='variation_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
